"""Configuration constants and environment variable names."""

# Authentication
ENV_API_KEY = "ARIZE_API_KEY"

# Server configuration env vars
ENV_REGION = "ARIZE_REGION"
ENV_API_HOST = "ARIZE_API_HOST"
ENV_API_SCHEME = "ARIZE_API_SCHEME"
ENV_OTLP_HOST = "ARIZE_OTLP_HOST"
ENV_OTLP_SCHEME = "ARIZE_OTLP_SCHEME"
ENV_FLIGHT_HOST = "ARIZE_FLIGHT_HOST"
ENV_FLIGHT_PORT = "ARIZE_FLIGHT_PORT"
ENV_FLIGHT_SCHEME = "ARIZE_FLIGHT_SCHEME"
ENV_SINGLE_HOST = "ARIZE_SINGLE_HOST"
ENV_SINGLE_PORT = "ARIZE_SINGLE_PORT"
ENV_BASE_DOMAIN = "ARIZE_BASE_DOMAIN"
ENV_PYARROW_MAX_CHUNKSIZE = "ARIZE_MAX_CHUNKSIZE"
ENV_REQUEST_VERIFY = "ARIZE_REQUEST_VERIFY"
ENV_MAX_HTTP_PAYLOAD_SIZE_MB = "ARIZE_MAX_HTTP_PAYLOAD_SIZE_MB"
ENV_ARIZE_DIRECTORY = "ARIZE_DIRECTORY"
ENV_ENABLE_CACHING = "ARIZE_ENABLE_CACHING"

# Server configuration default values
DEFAULT_API_HOST = "api.arize.com"  # NOTE: Must not prefix with https://
DEFAULT_API_SCHEME = "https"
DEFAULT_OTLP_HOST = "otlp.arize.com"  # NOTE: Must not prefix with https://
DEFAULT_OTLP_SCHEME = "https"
DEFAULT_FLIGHT_HOST = "flight.arize.com"  # NOTE: Must not prefix with https://
DEFAULT_FLIGHT_PORT = 443
DEFAULT_FLIGHT_SCHEME = "grpc+tls"
DEFAULT_PYARROW_MAX_CHUNKSIZE = 10_000
DEFAULT_REQUEST_VERIFY = True
DEFAULT_MAX_HTTP_PAYLOAD_SIZE_MB = 100
DEFAULT_ARIZE_DIRECTORY = "~/.arize"
DEFAULT_ENABLE_CACHING = True

# ML Streaming configuration
ENV_STREAM_MAX_WORKERS = "ARIZE_STREAM_MAX_WORKERS"
ENV_STREAM_MAX_QUEUE_BOUND = "ARIZE_STREAM_MAX_QUEUE_BOUND"
DEFAULT_STREAM_MAX_WORKERS = 8
DEFAULT_STREAM_MAX_QUEUE_BOUND = 5000

# Logging
ENV_LOG_ENABLE = "ARIZE_LOG_ENABLE"
ENV_LOG_LEVEL = "ARIZE_LOG_LEVEL"
ENV_LOG_STRUCTURED = "ARIZE_LOG_STRUCTURED"
DEFAULT_LOG_ENABLE = True
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_STRUCTURED = False
