# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AiIntegrationAuthType(str, Enum):
    """
    The authentication method for this integration
    """

    """
    allowed enum values
    """
    DEFAULT = 'default'
    PROXY_WITH_HEADERS = 'proxy_with_headers'
    BEARER_TOKEN = 'bearer_token'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AiIntegrationAuthType from a JSON string"""
        return cls(json.loads(json_str))


