# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from arize._generated.api_client.models.custom_baseline_config import CustomBaselineConfig
from arize._generated.api_client.models.model_baseline_config import ModelBaselineConfig
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

BASELINECONFIG_ONE_OF_SCHEMAS = ["CustomBaselineConfig", "ModelBaselineConfig"]

class BaselineConfig(BaseModel):
    """
    The comparison dataset configuration used by drift and comparison-based data quality monitors. The `type` field determines whether the comparison dataset uses the model's primary baseline or a custom fixed or moving window.
    """
    # data type: ModelBaselineConfig
    oneof_schema_1_validator: Optional[ModelBaselineConfig] = None
    # data type: CustomBaselineConfig
    oneof_schema_2_validator: Optional[CustomBaselineConfig] = None
    actual_instance: Optional[Union[CustomBaselineConfig, ModelBaselineConfig]] = None
    one_of_schemas: Set[str] = { "CustomBaselineConfig", "ModelBaselineConfig" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = BaselineConfig.model_construct()
        error_messages = []
        match = 0
        # validate data type: ModelBaselineConfig
        if not isinstance(v, ModelBaselineConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelBaselineConfig`")
        else:
            match += 1
        # validate data type: CustomBaselineConfig
        if not isinstance(v, CustomBaselineConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomBaselineConfig`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in BaselineConfig with oneOf schemas: CustomBaselineConfig, ModelBaselineConfig. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in BaselineConfig with oneOf schemas: CustomBaselineConfig, ModelBaselineConfig. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ModelBaselineConfig
        try:
            instance.actual_instance = ModelBaselineConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CustomBaselineConfig
        try:
            instance.actual_instance = CustomBaselineConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into BaselineConfig with oneOf schemas: CustomBaselineConfig, ModelBaselineConfig. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into BaselineConfig with oneOf schemas: CustomBaselineConfig, ModelBaselineConfig. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CustomBaselineConfig, ModelBaselineConfig]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


