# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from arize._generated.api_client.models.webhook_auth_type import WebhookAuthType
from typing import Optional, Set
from typing_extensions import Self

class CreateWebhookResponse(BaseModel):
    """
    The created webhook, plus `signing_secret` for `HMAC_SHA256` webhooks — the only time the secret is ever returned. 
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for the webhook")
    organization_id: StrictStr = Field(description="The unique identifier of the organization that owns the webhook")
    name: Annotated[str, Field(strict=True, max_length=255)] = Field(description="Name of the webhook (unique within the organization)")
    description: StrictStr = Field(description="A brief description of the webhook's purpose. Defaults to an empty string.")
    url: StrictStr = Field(description="The HTTPS endpoint events are delivered to")
    auth_type: WebhookAuthType = Field(description="How deliveries from this webhook are authenticated. Fixed at creation.")
    signing_secret: Optional[StrictStr] = Field(default=None, description="The secret used to verify delivery signatures. **Only returned once**, in this response, when `auth_type` is `HMAC_SHA256`. Store it securely — it cannot be retrieved again; only a redacted hint (`signing_secret_hint`) is readable afterwards. Absent for `BEARER` webhooks. ")
    signing_secret_hint: Optional[StrictStr] = Field(default=None, description="Redacted hint of the signing secret (e.g. `whsec_…abcd`), useful for identifying which secret the webhook uses. Present only for `HMAC_SHA256` webhooks. ")
    timeout_ms: Annotated[int, Field(le=60000, strict=True, ge=1000)] = Field(description="How long a delivery request may run before it is abandoned, in milliseconds. Defaults to 30000.")
    headers: Dict[str, StrictStr] = Field(description="Custom HTTP headers sent with each delivery request")
    created_at: datetime = Field(description="Timestamp for when the webhook was created")
    updated_at: datetime = Field(description="Timestamp for when the webhook was last updated")
    created_by_user_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the user who created the webhook. Absent when that user has since been removed from the account.")
    __properties: ClassVar[List[str]] = ["id", "organization_id", "name", "description", "url", "auth_type", "signing_secret", "signing_secret_hint", "timeout_ms", "headers", "created_at", "updated_at", "created_by_user_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateWebhookResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateWebhookResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)


        _obj = cls.model_validate({
            "id": obj.get("id"),
            "organization_id": obj.get("organization_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "url": obj.get("url"),
            "auth_type": obj.get("auth_type"),
            "signing_secret": obj.get("signing_secret"),
            "signing_secret_hint": obj.get("signing_secret_hint"),
            "timeout_ms": obj.get("timeout_ms"),
            "headers": obj.get("headers"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "created_by_user_id": obj.get("created_by_user_id")
        })
        return _obj


