# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from arize._generated.api_client.models.annotation_queue_record_input import AnnotationQueueRecordInput
from arize._generated.api_client.models.assignment_method import AssignmentMethod
from typing import Optional, Set
from typing_extensions import Self

class CreateAnnotationQueueRequestBody(BaseModel):
    """
    CreateAnnotationQueueRequestBody
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=255)] = Field(description="The name of the annotation queue. Must be unique within the space for active queues.")
    space_id: StrictStr = Field(description="The space ID that the annotation queue belongs to")
    instructions: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, description="Instructions for annotators working on this queue")
    annotation_config_ids: Annotated[List[StrictStr], Field(min_length=1)] = Field(description="IDs of annotation configs to associate with this queue. All configs must belong to the same space.")
    annotator_emails: Annotated[List[StrictStr], Field(min_length=1)] = Field(description="Email addresses of annotators to assign to the queue. Emails are resolved to user IDs server-side.")
    assignment_method: Optional[AssignmentMethod] = AssignmentMethod.ALL
    record_sources: Optional[Annotated[List[AnnotationQueueRecordInput], Field(max_length=2)]] = Field(default=None, description="Record sources to add to the annotation queue on creation. At most 2 record sources (projects or datasets) may be provided in a single create request. Additional records from other sources can be added after creation.")
    __properties: ClassVar[List[str]] = ["name", "space_id", "instructions", "annotation_config_ids", "annotator_emails", "assignment_method", "record_sources"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAnnotationQueueRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in record_sources (list)
        _items = []
        if self.record_sources:
            for _item_record_sources in self.record_sources:
                if _item_record_sources:
                    _items.append(_item_record_sources.to_dict())
            _dict['record_sources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAnnotationQueueRequestBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in CreateAnnotationQueueRequestBody) in the input: " + _key)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "space_id": obj.get("space_id"),
            "instructions": obj.get("instructions"),
            "annotation_config_ids": obj.get("annotation_config_ids"),
            "annotator_emails": obj.get("annotator_emails"),
            "assignment_method": obj.get("assignment_method") if obj.get("assignment_method") is not None else AssignmentMethod.ALL,
            "record_sources": [AnnotationQueueRecordInput.from_dict(_item) for _item in obj["record_sources"]] if obj.get("record_sources") is not None else None
        })
        return _obj


