# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EvaluatorType(str, Enum):
    """
    The evaluator type: `template` (LLM-based) or `code` (managed built-in evaluators or custom Python code — both are subtypes of `code`, discriminated by the nested `CodeConfig.type` = `managed` | `custom`). Applies to both the parent `Evaluator.type` field and every version's `type` discriminator — a version's `type` must always match its parent evaluator's `type`. 
    """

    """
    allowed enum values
    """
    TEMPLATE = 'template'
    CODE = 'code'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EvaluatorType from a JSON string"""
        return cls(json.loads(json_str))


