# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class EvaluatorLlmConfig(BaseModel):
    """
    EvaluatorLlmConfig
    """ # noqa: E501
    ai_integration_id: StrictStr = Field(description="AI integration global ID (base64)")
    model_name: StrictStr = Field(description="Model name (e.g. gpt-4o)")
    invocation_parameters: Dict[str, Any] = Field(description="Parameters for the LLM call (e.g. temperature, max_tokens)")
    provider_parameters: Dict[str, Any] = Field(description="Provider-specific parameters")
    __properties: ClassVar[List[str]] = ["ai_integration_id", "model_name", "invocation_parameters", "provider_parameters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EvaluatorLlmConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EvaluatorLlmConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in EvaluatorLlmConfig) in the input: " + _key)

        _obj = cls.model_validate({
            "ai_integration_id": obj.get("ai_integration_id"),
            "model_name": obj.get("model_name"),
            "invocation_parameters": obj.get("invocation_parameters"),
            "provider_parameters": obj.get("provider_parameters")
        })
        return _obj


