# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InviteMode(str, Enum):
    """
    Controls how the user is invited to the account. - `none` — add the user directly with no invitation email (for SSO-only accounts). - `email_link` — send the user an email with a verification link to complete registration. - `temporary_password` — issue a temporary password returned in the `POST /v2/users` response body; the user must reset it on first login. **Treat this value as a secret** — see `UserCreatedResponse.temporary_password` for security guidance. 
    """

    """
    allowed enum values
    """
    NONE = 'none'
    EMAIL_LINK = 'email_link'
    TEMPORARY_PASSWORD = 'temporary_password'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InviteMode from a JSON string"""
        return cls(json.loads(json_str))


