# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from arize._generated.api_client.models.response_format import ResponseFormat
from arize._generated.api_client.models.tool_config import ToolConfig
from typing import Optional, Set
from typing_extensions import Self

class InvocationParams(BaseModel):
    """
    Parameters for the LLM invocation
    """ # noqa: E501
    temperature: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Sampling temperature (higher = more random)")
    max_tokens: Optional[StrictInt] = Field(default=None, description="Maximum number of tokens to generate")
    max_completion_tokens: Optional[StrictInt] = Field(default=None, description="Maximum number of completion tokens to generate")
    top_p: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Nucleus sampling parameter")
    frequency_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Frequency penalty (-2.0 to 2.0)")
    presence_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Presence penalty (-2.0 to 2.0)")
    stop: Optional[List[StrictStr]] = Field(default=None, description="Stop sequences")
    response_format: Optional[ResponseFormat] = Field(default=None, description="Response format configuration. Optional. When omitted, no structured output constraint is applied (the provider's default plain-text behavior is used).")
    tool_config: Optional[ToolConfig] = Field(default=None, description="Tool configuration for the LLM invocation. Optional. When omitted, no tools are made available to the model.")
    top_k: Optional[StrictInt] = Field(default=None, description="Top-K sampling parameter. A top-K of 1 means the next selected token is the most probable (greedy decoding).")
    thinking_level: Optional[StrictStr] = Field(default=None, description="Controls how much reasoning the model performs before responding. Supported by Gemini 3.x models. Accepted values: 'low', 'high'.")
    thinking_budget: Optional[StrictInt] = Field(default=None, description="Maximum tokens the model may use for internal reasoning. Supported by Gemini 2.5 models. Range: 0-24576 (Flash/Flash-Lite) or 128-32768 (Pro). Set 0 to disable thinking on Flash models.")
    reasoning_effort: Optional[StrictStr] = Field(default=None, description="Controls how much reasoning the model performs before responding. Supported by OpenAI o-series and GPT-5 models. o-series: 'low' | 'medium' | 'high'. GPT-5: 'none' | 'low' | 'medium' | 'high' | 'xhigh'.")
    verbosity: Optional[StrictStr] = Field(default=None, description="Controls the verbosity of model output. Supported by OpenAI GPT-5 series. Accepted values: 'low' | 'medium' | 'high'.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["temperature", "max_tokens", "max_completion_tokens", "top_p", "frequency_penalty", "presence_penalty", "stop", "response_format", "tool_config", "top_k", "thinking_level", "thinking_budget", "reasoning_effort", "verbosity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvocationParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of response_format
        if self.response_format:
            _dict['response_format'] = self.response_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tool_config
        if self.tool_config:
            _dict['tool_config'] = self.tool_config.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvocationParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "temperature": obj.get("temperature"),
            "max_tokens": obj.get("max_tokens"),
            "max_completion_tokens": obj.get("max_completion_tokens"),
            "top_p": obj.get("top_p"),
            "frequency_penalty": obj.get("frequency_penalty"),
            "presence_penalty": obj.get("presence_penalty"),
            "stop": obj.get("stop"),
            "response_format": ResponseFormat.from_dict(obj["response_format"]) if obj.get("response_format") is not None else None,
            "tool_config": ToolConfig.from_dict(obj["tool_config"]) if obj.get("tool_config") is not None else None,
            "top_k": obj.get("top_k"),
            "thinking_level": obj.get("thinking_level"),
            "thinking_budget": obj.get("thinking_budget"),
            "reasoning_effort": obj.get("reasoning_effort"),
            "verbosity": obj.get("verbosity")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


