# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PerformanceMetric(str, Enum):
    """
    The model performance metric. 
    """

    """
    allowed enum values
    """
    ACCURACY = 'ACCURACY'
    CALIBRATION = 'CALIBRATION'
    F_1 = 'F_1'
    FALSE_NEGATIVE_DENSITY = 'FALSE_NEGATIVE_DENSITY'
    FALSE_NEGATIVE_RATE = 'FALSE_NEGATIVE_RATE'
    FALSE_POSITIVE_RATE = 'FALSE_POSITIVE_RATE'
    PRECISION = 'PRECISION'
    RECALL = 'RECALL'
    SENSITIVITY = 'SENSITIVITY'
    SPECIFICITY = 'SPECIFICITY'
    MICRO_AVERAGED_PRECISION = 'MICRO_AVERAGED_PRECISION'
    MACRO_AVERAGED_PRECISION = 'MACRO_AVERAGED_PRECISION'
    MULTI_CLASS_PRECISION = 'MULTI_CLASS_PRECISION'
    MICRO_AVERAGED_RECALL = 'MICRO_AVERAGED_RECALL'
    MACRO_AVERAGED_RECALL = 'MACRO_AVERAGED_RECALL'
    MULTI_CLASS_RECALL = 'MULTI_CLASS_RECALL'
    ACTUALS_AVERAGE = 'ACTUALS_AVERAGE'
    MAE = 'MAE'
    MAPE = 'MAPE'
    MEAN_ERROR = 'MEAN_ERROR'
    MSE = 'MSE'
    PREDICTION_AVERAGE = 'PREDICTION_AVERAGE'
    RMSE = 'RMSE'
    R_SQUARED = 'R_SQUARED'
    SMAPE = 'SMAPE'
    WAPE = 'WAPE'
    MASE = 'MASE'
    AUC = 'AUC'
    LOG_LOSS = 'LOG_LOSS'
    NDCG = 'NDCG'
    PR_AUC = 'PR_AUC'
    GROUP_AUC = 'GROUP_AUC'
    MRR = 'MRR'
    RANKING_MAP = 'RANKING_MAP'
    RANKING_RECALL = 'RANKING_RECALL'
    RANKING_PRECISION = 'RANKING_PRECISION'
    DISPARATE_IMPACT = 'DISPARATE_IMPACT'
    FALSE_POSITIVE_RATE_PARITY = 'FALSE_POSITIVE_RATE_PARITY'
    RECALL_PARITY = 'RECALL_PARITY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PerformanceMetric from a JSON string"""
        return cls(json.loads(json_str))


