# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from arize._generated.api_client.models.tasks_create_request_evaluators_inner import TasksCreateRequestEvaluatorsInner
from typing import Optional, Set
from typing_extensions import Self

class TasksUpdateRequest(BaseModel):
    """
    TasksUpdateRequest
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="New task name")
    sampling_rate: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Sampling rate between 0 and 1. Only applicable for project-based tasks.")
    is_continuous: Optional[StrictBool] = Field(default=None, description="Whether the task runs continuously. Only applicable for project-based tasks.")
    query_filter: Optional[StrictStr] = Field(default=None, description="Task-level query filter applied to all data. Pass null to clear.")
    evaluators: Optional[Annotated[List[TasksCreateRequestEvaluatorsInner], Field(min_length=1)]] = Field(default=None, description="Replaces the entire evaluator list. At least one evaluator is required when provided.")
    __properties: ClassVar[List[str]] = ["name", "sampling_rate", "is_continuous", "query_filter", "evaluators"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TasksUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in evaluators (list)
        _items = []
        if self.evaluators:
            for _item_evaluators in self.evaluators:
                if _item_evaluators:
                    _items.append(_item_evaluators.to_dict())
            _dict['evaluators'] = _items
        # set to None if query_filter (nullable) is None
        # and model_fields_set contains the field
        if self.query_filter is None and "query_filter" in self.model_fields_set:
            _dict['query_filter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TasksUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in TasksUpdateRequest) in the input: " + _key)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "sampling_rate": obj.get("sampling_rate"),
            "is_continuous": obj.get("is_continuous"),
            "query_filter": obj.get("query_filter"),
            "evaluators": [TasksCreateRequestEvaluatorsInner.from_dict(_item) for _item in obj["evaluators"]] if obj.get("evaluators") is not None else None
        })
        return _obj


