# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from arize._generated.api_client.models.categorical_annotation_config_update import CategoricalAnnotationConfigUpdate
from arize._generated.api_client.models.continuous_annotation_config_update import ContinuousAnnotationConfigUpdate
from arize._generated.api_client.models.freeform_annotation_config_update import FreeformAnnotationConfigUpdate
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

UPDATEANNOTATIONCONFIGREQUESTBODY_ONE_OF_SCHEMAS = ["CategoricalAnnotationConfigUpdate", "ContinuousAnnotationConfigUpdate", "FreeformAnnotationConfigUpdate"]

class UpdateAnnotationConfigRequestBody(BaseModel):
    """
    UpdateAnnotationConfigRequestBody
    """
    # data type: ContinuousAnnotationConfigUpdate
    oneof_schema_1_validator: Optional[ContinuousAnnotationConfigUpdate] = None
    # data type: CategoricalAnnotationConfigUpdate
    oneof_schema_2_validator: Optional[CategoricalAnnotationConfigUpdate] = None
    # data type: FreeformAnnotationConfigUpdate
    oneof_schema_3_validator: Optional[FreeformAnnotationConfigUpdate] = None
    actual_instance: Optional[Union[CategoricalAnnotationConfigUpdate, ContinuousAnnotationConfigUpdate, FreeformAnnotationConfigUpdate]] = None
    one_of_schemas: Set[str] = { "CategoricalAnnotationConfigUpdate", "ContinuousAnnotationConfigUpdate", "FreeformAnnotationConfigUpdate" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = UpdateAnnotationConfigRequestBody.model_construct()
        error_messages = []
        match = 0
        # validate data type: ContinuousAnnotationConfigUpdate
        if not isinstance(v, ContinuousAnnotationConfigUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ContinuousAnnotationConfigUpdate`")
        else:
            match += 1
        # validate data type: CategoricalAnnotationConfigUpdate
        if not isinstance(v, CategoricalAnnotationConfigUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CategoricalAnnotationConfigUpdate`")
        else:
            match += 1
        # validate data type: FreeformAnnotationConfigUpdate
        if not isinstance(v, FreeformAnnotationConfigUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FreeformAnnotationConfigUpdate`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UpdateAnnotationConfigRequestBody with oneOf schemas: CategoricalAnnotationConfigUpdate, ContinuousAnnotationConfigUpdate, FreeformAnnotationConfigUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UpdateAnnotationConfigRequestBody with oneOf schemas: CategoricalAnnotationConfigUpdate, ContinuousAnnotationConfigUpdate, FreeformAnnotationConfigUpdate. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ContinuousAnnotationConfigUpdate
        try:
            instance.actual_instance = ContinuousAnnotationConfigUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CategoricalAnnotationConfigUpdate
        try:
            instance.actual_instance = CategoricalAnnotationConfigUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FreeformAnnotationConfigUpdate
        try:
            instance.actual_instance = FreeformAnnotationConfigUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UpdateAnnotationConfigRequestBody with oneOf schemas: CategoricalAnnotationConfigUpdate, ContinuousAnnotationConfigUpdate, FreeformAnnotationConfigUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UpdateAnnotationConfigRequestBody with oneOf schemas: CategoricalAnnotationConfigUpdate, ContinuousAnnotationConfigUpdate, FreeformAnnotationConfigUpdate. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CategoricalAnnotationConfigUpdate, ContinuousAnnotationConfigUpdate, FreeformAnnotationConfigUpdate]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


