# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UpdateWebhookRequest(BaseModel):
    """
    UpdateWebhookRequest
    """ # noqa: E501
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Updated name of the webhook (must be unique within the organization)")
    description: Optional[StrictStr] = Field(default=None, description="Updated description of the webhook. Set to `null` to clear it.")
    url: Optional[StrictStr] = Field(default=None, description="Updated HTTPS endpoint events are delivered to")
    auth_token: Optional[StrictStr] = Field(default=None, description="Replacement `Authorization` header value sent with each delivery request, e.g. `Bearer my-token`. Sent verbatim — include the `Bearer ` prefix if your endpoint expects one. Only valid when the webhook's `auth_type` is `BEARER`. Write-only: never returned in any response. ")
    timeout_ms: Optional[Annotated[int, Field(le=60000, strict=True, ge=1000)]] = Field(default=None, description="Updated delivery timeout in milliseconds")
    headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Replacement custom HTTP headers, as a map of at most 20 header names to values. Replaces the whole header map; headers not included are removed. ")
    __properties: ClassVar[List[str]] = ["name", "description", "url", "auth_token", "timeout_ms", "headers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateWebhookRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateWebhookRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in UpdateWebhookRequest) in the input: " + _key)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "url": obj.get("url"),
            "auth_token": obj.get("auth_token"),
            "timeout_ms": obj.get("timeout_ms"),
            "headers": obj.get("headers")
        })
        return _obj


