# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class WebhookDeliveryAttempt(BaseModel):
    """
    A single attempt to deliver an event to a webhook's endpoint.
    """ # noqa: E501
    event_id: StrictStr = Field(description="Unique identifier of the event that triggered this delivery")
    attempt_number: Annotated[int, Field(strict=True, ge=1)] = Field(description="Which attempt this was for the event, starting at 1. Failed deliveries are retried.")
    payload: Dict[str, Any] = Field(description="The JSON payload sent to the webhook's endpoint")
    status_code: Optional[StrictInt] = Field(default=None, description="HTTP status code returned by the endpoint. `null` when no response was received.")
    error_message: Optional[StrictStr] = Field(default=None, description="Why the delivery failed. `null` for successful deliveries.")
    created_at: datetime = Field(description="Timestamp for when the delivery was attempted")
    __properties: ClassVar[List[str]] = ["event_id", "attempt_number", "payload", "status_code", "error_message", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookDeliveryAttempt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if status_code (nullable) is None
        # and model_fields_set contains the field
        if self.status_code is None and "status_code" in self.model_fields_set:
            _dict['status_code'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookDeliveryAttempt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)


        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "attempt_number": obj.get("attempt_number"),
            "payload": obj.get("payload"),
            "status_code": obj.get("status_code"),
            "error_message": obj.get("error_message"),
            "created_at": obj.get("created_at")
        })
        return _obj


