# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from datetime import datetime, timezone

from arize._generated.api_client.models.api_key import ApiKey


class TestApiKey(unittest.TestCase):
    """ApiKey unit test stubs"""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def test_api_key_required_only(self) -> None:
        """ApiKey with required fields only."""
        created = datetime(2024, 1, 15, 12, 0, 0, tzinfo=timezone.utc)
        key = ApiKey(
            id="key-id-123",
            name="My Key",
            key_type="user",
            status="active",
            redacted_key="ak-abc...xyz",
            created_at=created,
            created_by_user_id="user-id-456",
        )
        assert key.id == "key-id-123"
        assert key.name == "My Key"
        assert key.key_type == "user"
        assert key.status == "active"
        assert key.redacted_key == "ak-abc...xyz"
        assert key.created_by_user_id == "user-id-456"
        assert key.description is None
        assert key.expires_at is None

    def test_api_key_with_optional(self) -> None:
        """ApiKey with optional description and expires_at."""
        created = datetime(2024, 1, 15, 12, 0, 0, tzinfo=timezone.utc)
        expires = datetime(2025, 1, 15, 12, 0, 0, tzinfo=timezone.utc)
        key = ApiKey(
            id="key-id-123",
            name="Service Key",
            key_type="service",
            status="active",
            redacted_key="ak-svc...xyz",
            created_at=created,
            created_by_user_id="user-id-456",
            description="CI/CD key",
            expires_at=expires,
        )
        assert key.description == "CI/CD key"
        assert key.expires_at == expires
        assert key.key_type == "service"

    def test_api_key_from_dict(self) -> None:
        """ApiKey.from_dict round-trip."""
        created = "2024-01-15T12:00:00+00:00"
        data = {
            "id": "key-id-123",
            "name": "My Key",
            "key_type": "user",
            "status": "active",
            "redacted_key": "ak-abc...xyz",
            "created_at": created,
            "created_by_user_id": "user-id-456",
        }
        key = ApiKey.from_dict(data)
        assert key is not None
        assert key.id == "key-id-123"
        assert key.name == "My Key"
        assert key.to_dict()["id"] == "key-id-123"


if __name__ == "__main__":
    unittest.main()
