# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.list_task_runs_response import ListTaskRunsResponse

class TestListTaskRunsResponse(unittest.TestCase):
    """ListTaskRunsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTaskRunsResponse:
        """Test ListTaskRunsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTaskRunsResponse`
        """
        model = ListTaskRunsResponse()
        if include_optional:
            return ListTaskRunsResponse(
                task_runs = [
                    arize._generated.api_client.models.task_run.TaskRun(
                        id = '', 
                        task_id = '', 
                        experiment_id = '', 
                        status = 'PENDING', 
                        run_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        run_finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        num_successes = 56, 
                        num_errors = 56, 
                        num_skipped = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        failure_reason = '', )
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, )
            )
        else:
            return ListTaskRunsResponse(
                task_runs = [
                    arize._generated.api_client.models.task_run.TaskRun(
                        id = '', 
                        task_id = '', 
                        experiment_id = '', 
                        status = 'PENDING', 
                        run_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        run_finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        num_successes = 56, 
                        num_errors = 56, 
                        num_skipped = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        failure_reason = '', )
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, ),
        )
        """

    def testListTaskRunsResponse(self):
        """Test ListTaskRunsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
