# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.api.traces_api import TracesApi


class TestTracesApi(unittest.TestCase):
    """TracesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TracesApi()

    def tearDown(self) -> None:
        pass

    def test_list_traces(self) -> None:
        """Test case for list_traces

        List traces
        """
        pass


if __name__ == '__main__':
    unittest.main()
