# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.list_api_keys_response import ListApiKeysResponse

class TestListApiKeysResponse(unittest.TestCase):
    """ListApiKeysResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListApiKeysResponse:
        """Test ListApiKeysResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListApiKeysResponse`
        """
        model = ListApiKeysResponse()
        if include_optional:
            return ListApiKeysResponse(
                api_keys = [
                    arize._generated.api_client.models.api_key_redacted.ApiKeyRedacted(
                        id = '', 
                        name = '', 
                        description = '', 
                        key_type = 'USER', 
                        status = 'ACTIVE', 
                        redacted_key = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, )
            )
        else:
            return ListApiKeysResponse(
                api_keys = [
                    arize._generated.api_client.models.api_key_redacted.ApiKeyRedacted(
                        id = '', 
                        name = '', 
                        description = '', 
                        key_type = 'USER', 
                        status = 'ACTIVE', 
                        redacted_key = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, ),
        )
        """

    def testListApiKeysResponse(self):
        """Test ListApiKeysResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
