# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.prompt_version_list_response import PromptVersionListResponse

class TestPromptVersionListResponse(unittest.TestCase):
    """PromptVersionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptVersionListResponse:
        """Test PromptVersionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptVersionListResponse`
        """
        model = PromptVersionListResponse()
        if include_optional:
            return PromptVersionListResponse(
                prompt_versions = [
                    arize._generated.api_client.models.prompt_version.PromptVersion(
                        id = '', 
                        prompt_id = '', 
                        commit_hash = '', 
                        commit_message = '', 
                        messages = [
                            arize._generated.api_client.models.llm_message.LLMMessage(
                                role = 'user', 
                                content = '', 
                                tool_call_id = '', 
                                tool_calls = [
                                    arize._generated.api_client.models.tool_call.ToolCall(
                                        id = '', 
                                        type = 'function', 
                                        function = arize._generated.api_client.models.tool_call_function.ToolCallFunction(
                                            name = '', 
                                            arguments = '', ), )
                                    ], )
                            ], 
                        input_variable_format = 'f_string', 
                        provider = 'open_ai', 
                        model = '', 
                        invocation_params = { }, 
                        provider_params = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        labels = [
                            ''
                            ], )
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, )
            )
        else:
            return PromptVersionListResponse(
                prompt_versions = [
                    arize._generated.api_client.models.prompt_version.PromptVersion(
                        id = '', 
                        prompt_id = '', 
                        commit_hash = '', 
                        commit_message = '', 
                        messages = [
                            arize._generated.api_client.models.llm_message.LLMMessage(
                                role = 'user', 
                                content = '', 
                                tool_call_id = '', 
                                tool_calls = [
                                    arize._generated.api_client.models.tool_call.ToolCall(
                                        id = '', 
                                        type = 'function', 
                                        function = arize._generated.api_client.models.tool_call_function.ToolCallFunction(
                                            name = '', 
                                            arguments = '', ), )
                                    ], )
                            ], 
                        input_variable_format = 'f_string', 
                        provider = 'open_ai', 
                        model = '', 
                        invocation_params = { }, 
                        provider_params = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        labels = [
                            ''
                            ], )
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, ),
        )
        """

    def testPromptVersionListResponse(self):
        """Test PromptVersionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
