# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.response_format_request import ResponseFormatRequest

class TestResponseFormatRequest(unittest.TestCase):
    """ResponseFormatRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseFormatRequest:
        """Test ResponseFormatRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseFormatRequest`
        """
        model = ResponseFormatRequest()
        if include_optional:
            return ResponseFormatRequest(
                type = 'TEXT',
                json_schema = arize._generated.api_client.models.json_schema_config_request.JsonSchemaConfigRequest(
                    name = '', 
                    description = '', 
                    schema = arize._generated.api_client.models.schema.schema(), 
                    strict = True, )
            )
        else:
            return ResponseFormatRequest(
        )
        """

    def testResponseFormatRequest(self):
        """Test ResponseFormatRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
