# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.prompt_versions_create_request import PromptVersionsCreateRequest

class TestPromptVersionsCreateRequest(unittest.TestCase):
    """PromptVersionsCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptVersionsCreateRequest:
        """Test PromptVersionsCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptVersionsCreateRequest`
        """
        model = PromptVersionsCreateRequest()
        if include_optional:
            return PromptVersionsCreateRequest(
                commit_message = '',
                input_variable_format = 'f_string',
                provider = 'open_ai',
                model = '',
                messages = [
                    arize._generated.api_client.models.llm_message.LLMMessage(
                        role = 'user', 
                        content = '', 
                        tool_call_id = '', 
                        tool_calls = [
                            arize._generated.api_client.models.tool_call.ToolCall(
                                id = '', 
                                type = 'function', 
                                function = arize._generated.api_client.models.tool_call_function.ToolCallFunction(
                                    name = '', 
                                    arguments = '', ), )
                            ], )
                    ],
                invocation_params = { },
                provider_params = { }
            )
        else:
            return PromptVersionsCreateRequest(
                commit_message = '',
                provider = 'open_ai',
                messages = [
                    arize._generated.api_client.models.llm_message.LLMMessage(
                        role = 'user', 
                        content = '', 
                        tool_call_id = '', 
                        tool_calls = [
                            arize._generated.api_client.models.tool_call.ToolCall(
                                id = '', 
                                type = 'function', 
                                function = arize._generated.api_client.models.tool_call_function.ToolCallFunction(
                                    name = '', 
                                    arguments = '', ), )
                            ], )
                    ],
        )
        """

    def testPromptVersionsCreateRequest(self):
        """Test PromptVersionsCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
