# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.api.annotation_queues_api import AnnotationQueuesApi


class TestAnnotationQueuesApi(unittest.TestCase):
    """AnnotationQueuesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnnotationQueuesApi()

    def tearDown(self) -> None:
        pass

    def test_annotation_queues_list(self) -> None:
        """Test case for annotation_queues_list

        List annotation queues
        """
        pass


if __name__ == '__main__':
    unittest.main()
