# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.monitor_filter import MonitorFilter

class TestMonitorFilter(unittest.TestCase):
    """MonitorFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorFilter:
        """Test MonitorFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorFilter`
        """
        model = MonitorFilter()
        if include_optional:
            return MonitorFilter(
                dimension = arize._generated.api_client.models.dimension.Dimension(
                    category = null, 
                    name = '', ),
                operator = 'greater_than',
                values = [
                    ''
                    ]
            )
        else:
            return MonitorFilter(
                dimension = arize._generated.api_client.models.dimension.Dimension(
                    category = null, 
                    name = '', ),
                operator = 'greater_than',
                values = [
                    ''
                    ],
        )
        """

    def testMonitorFilter(self):
        """Test MonitorFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
