# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.create_lite_llm_config import CreateLiteLlmConfig

class TestCreateLiteLlmConfig(unittest.TestCase):
    """CreateLiteLlmConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLiteLlmConfig:
        """Test CreateLiteLlmConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLiteLlmConfig`
        """
        model = CreateLiteLlmConfig()
        if include_optional:
            return CreateLiteLlmConfig(
                is_function_calling_enabled = True,
                provider = 'LITELLM',
                base_url = '',
                api_key = '',
                headers = {
                    'key' : ''
                    },
                model_names = [
                    ''
                    ]
            )
        else:
            return CreateLiteLlmConfig(
                provider = 'LITELLM',
                base_url = '',
                api_key = '',
        )
        """

    def testCreateLiteLlmConfig(self):
        """Test CreateLiteLlmConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
