# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.annotation_config_list_response import AnnotationConfigListResponse

class TestAnnotationConfigListResponse(unittest.TestCase):
    """AnnotationConfigListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationConfigListResponse:
        """Test AnnotationConfigListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationConfigListResponse`
        """
        model = AnnotationConfigListResponse()
        if include_optional:
            return AnnotationConfigListResponse(
                annotation_configs = [
                    { }
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, )
            )
        else:
            return AnnotationConfigListResponse(
                annotation_configs = [
                    { }
                    ],
                pagination = arize._generated.api_client.models.pagination_metadata.PaginationMetadata(
                    next_cursor = '', 
                    has_more = True, ),
        )
        """

    def testAnnotationConfigListResponse(self):
        """Test AnnotationConfigListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
