# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.update_evaluator_integration_request import UpdateEvaluatorIntegrationRequest

class TestUpdateEvaluatorIntegrationRequest(unittest.TestCase):
    """UpdateEvaluatorIntegrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateEvaluatorIntegrationRequest:
        """Test UpdateEvaluatorIntegrationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateEvaluatorIntegrationRequest`
        """
        model = UpdateEvaluatorIntegrationRequest()
        if include_optional:
            return UpdateEvaluatorIntegrationRequest(
                type = 'EVALUATOR',
                name = '',
                description = '',
                scopings = [
                    arize._generated.api_client.models.integration_scoping_request.IntegrationScopingRequest(
                        organization_id = '', 
                        space_id = '', )
                    ],
                config = arize._generated.api_client.models.update_evaluator_integration_config_input.UpdateEvaluatorIntegrationConfigInput(
                    endpoint = '', 
                    headers = {
                        'key' : ''
                        }, 
                    input_schema = { }, )
            )
        else:
            return UpdateEvaluatorIntegrationRequest(
                type = 'EVALUATOR',
        )
        """

    def testUpdateEvaluatorIntegrationRequest(self):
        """Test UpdateEvaluatorIntegrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
