# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.service_key_bot_user_org_assignment import ServiceKeyBotUserOrgAssignment

class TestServiceKeyBotUserOrgAssignment(unittest.TestCase):
    """ServiceKeyBotUserOrgAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceKeyBotUserOrgAssignment:
        """Test ServiceKeyBotUserOrgAssignment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceKeyBotUserOrgAssignment`
        """
        model = ServiceKeyBotUserOrgAssignment()
        if include_optional:
            return ServiceKeyBotUserOrgAssignment(
                org_id = 'T3JnYW5pemF0aW9uOjEwMDE6eFl6Vw',
                role = None,
                spaces = [
                    arize._generated.api_client.models.service_key_bot_user_space_assignment.ServiceKeyBotUserSpaceAssignment(
                        space_id = 'U3BhY2U6MjAwMTphQmNE', 
                        role = null, )
                    ]
            )
        else:
            return ServiceKeyBotUserOrgAssignment(
                org_id = 'T3JnYW5pemF0aW9uOjEwMDE6eFl6Vw',
                role = None,
                spaces = [
                    arize._generated.api_client.models.service_key_bot_user_space_assignment.ServiceKeyBotUserSpaceAssignment(
                        space_id = 'U3BhY2U6MjAwMTphQmNE', 
                        role = null, )
                    ],
        )
        """

    def testServiceKeyBotUserOrgAssignment(self):
        """Test ServiceKeyBotUserOrgAssignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
