# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.api.prompts_api import PromptsApi


class TestPromptsApi(unittest.TestCase):
    """PromptsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PromptsApi()

    def tearDown(self) -> None:
        pass

    def test_prompt_labels_get(self) -> None:
        """Test case for prompt_labels_get

        Resolve a label to a prompt version
        """
        pass

    def test_prompt_version_labels_delete(self) -> None:
        """Test case for prompt_version_labels_delete

        Remove a label from a prompt version
        """
        pass

    def test_prompt_version_labels_set(self) -> None:
        """Test case for prompt_version_labels_set

        Set labels on a prompt version
        """
        pass

    def test_prompt_versions_create(self) -> None:
        """Test case for prompt_versions_create

        Create a prompt version
        """
        pass

    def test_prompt_versions_get(self) -> None:
        """Test case for prompt_versions_get

        Get a prompt version
        """
        pass

    def test_prompt_versions_list(self) -> None:
        """Test case for prompt_versions_list

        List prompt versions
        """
        pass

    def test_prompts_create(self) -> None:
        """Test case for prompts_create

        Create a prompt
        """
        pass

    def test_prompts_delete(self) -> None:
        """Test case for prompts_delete

        Delete a prompt
        """
        pass

    def test_prompts_get(self) -> None:
        """Test case for prompts_get

        Get a prompt
        """
        pass

    def test_prompts_list(self) -> None:
        """Test case for prompts_list

        List prompts
        """
        pass

    def test_prompts_update(self) -> None:
        """Test case for prompts_update

        Update a prompt
        """
        pass


if __name__ == '__main__':
    unittest.main()
