# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.create_aws_bedrock_proxy_with_headers_auth import CreateAwsBedrockProxyWithHeadersAuth

class TestCreateAwsBedrockProxyWithHeadersAuth(unittest.TestCase):
    """CreateAwsBedrockProxyWithHeadersAuth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAwsBedrockProxyWithHeadersAuth:
        """Test CreateAwsBedrockProxyWithHeadersAuth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAwsBedrockProxyWithHeadersAuth`
        """
        model = CreateAwsBedrockProxyWithHeadersAuth()
        if include_optional:
            return CreateAwsBedrockProxyWithHeadersAuth(
                auth_type = 'proxy_with_headers',
                base_url = '',
                headers = {
                    'key' : ''
                    }
            )
        else:
            return CreateAwsBedrockProxyWithHeadersAuth(
                auth_type = 'proxy_with_headers',
                base_url = '',
        )
        """

    def testCreateAwsBedrockProxyWithHeadersAuth(self):
        """Test CreateAwsBedrockProxyWithHeadersAuth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
