# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.api.prompts_api import PromptsApi


class TestPromptsApi(unittest.TestCase):
    """PromptsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PromptsApi()

    def tearDown(self) -> None:
        pass

    def test_create_prompt(self) -> None:
        """Test case for create_prompt

        Create a prompt
        """
        pass

    def test_create_prompt_version(self) -> None:
        """Test case for create_prompt_version

        Create a prompt version
        """
        pass

    def test_delete_prompt(self) -> None:
        """Test case for delete_prompt

        Delete a prompt
        """
        pass

    def test_delete_prompt_version_label(self) -> None:
        """Test case for delete_prompt_version_label

        Remove a label from a prompt version
        """
        pass

    def test_get_prompt(self) -> None:
        """Test case for get_prompt

        Get a prompt
        """
        pass

    def test_get_prompt_label(self) -> None:
        """Test case for get_prompt_label

        Resolve a label to a prompt version
        """
        pass

    def test_get_prompt_version(self) -> None:
        """Test case for get_prompt_version

        Get a prompt version
        """
        pass

    def test_list_prompt_versions(self) -> None:
        """Test case for list_prompt_versions

        List prompt versions
        """
        pass

    def test_list_prompts(self) -> None:
        """Test case for list_prompts

        List prompts
        """
        pass

    def test_set_prompt_version_label(self) -> None:
        """Test case for set_prompt_version_label

        Set labels on a prompt version
        """
        pass

    def test_update_prompt(self) -> None:
        """Test case for update_prompt

        Update a prompt
        """
        pass


if __name__ == '__main__':
    unittest.main()
