# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.evaluators_create_request import EvaluatorsCreateRequest

class TestEvaluatorsCreateRequest(unittest.TestCase):
    """EvaluatorsCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvaluatorsCreateRequest:
        """Test EvaluatorsCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvaluatorsCreateRequest`
        """
        model = EvaluatorsCreateRequest()
        if include_optional:
            return EvaluatorsCreateRequest(
                space_id = '',
                name = '',
                description = '',
                type = 'template',
                version = arize._generated.api_client.models.evaluators_create_request_version.evaluators_create_request_version(
                    commit_message = '', 
                    template_config = arize._generated.api_client.models.template_config.TemplateConfig(
                        name = '', 
                        template = '', 
                        include_explanations = True, 
                        use_function_calling_if_available = True, 
                        classification_choices = {
                            'key' : 1.337
                            }, 
                        direction = 'maximize', 
                        data_granularity = 'span', 
                        llm_config = arize._generated.api_client.models.evaluator_llm_config.EvaluatorLlmConfig(
                            ai_integration_id = '', 
                            model_name = '', 
                            invocation_parameters = { }, 
                            provider_parameters = { }, ), ), )
            )
        else:
            return EvaluatorsCreateRequest(
                space_id = '',
                name = '',
                type = 'template',
                version = arize._generated.api_client.models.evaluators_create_request_version.evaluators_create_request_version(
                    commit_message = '', 
                    template_config = arize._generated.api_client.models.template_config.TemplateConfig(
                        name = '', 
                        template = '', 
                        include_explanations = True, 
                        use_function_calling_if_available = True, 
                        classification_choices = {
                            'key' : 1.337
                            }, 
                        direction = 'maximize', 
                        data_granularity = 'span', 
                        llm_config = arize._generated.api_client.models.evaluator_llm_config.EvaluatorLlmConfig(
                            ai_integration_id = '', 
                            model_name = '', 
                            invocation_parameters = { }, 
                            provider_parameters = { }, ), ), ),
        )
        """

    def testEvaluatorsCreateRequest(self):
        """Test EvaluatorsCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
