# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.remote_config_input import RemoteConfigInput

class TestRemoteConfigInput(unittest.TestCase):
    """RemoteConfigInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoteConfigInput:
        """Test RemoteConfigInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoteConfigInput`
        """
        model = RemoteConfigInput()
        if include_optional:
            return RemoteConfigInput(
                integration_id = ''
            )
        else:
            return RemoteConfigInput(
                integration_id = '',
        )
        """

    def testRemoteConfigInput(self):
        """Test RemoteConfigInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
