# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Create a webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete a webhook
        """
        pass

    def test_get_webhook(self) -> None:
        """Test case for get_webhook

        Get a webhook
        """
        pass

    def test_list_webhook_delivery_attempts(self) -> None:
        """Test case for list_webhook_delivery_attempts

        List a webhook's delivery attempts
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List webhooks
        """
        pass

    def test_test_webhook(self) -> None:
        """Test case for test_webhook

        Send a test event to a webhook
        """
        pass

    def test_update_webhook(self) -> None:
        """Test case for update_webhook

        Update a webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
