# coding: utf-8

"""
    Arize REST API

    API specification for the backend data server. The API is hosted globally at https://api.arize.com/v2 or in your own environment. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arize._generated.api_client.models.evaluator_version_template import EvaluatorVersionTemplate

class TestEvaluatorVersionTemplate(unittest.TestCase):
    """EvaluatorVersionTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvaluatorVersionTemplate:
        """Test EvaluatorVersionTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvaluatorVersionTemplate`
        """
        model = EvaluatorVersionTemplate()
        if include_optional:
            return EvaluatorVersionTemplate(
                id = '',
                evaluator_id = '',
                commit_hash = '',
                commit_message = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user_id = '',
                type = 'template',
                template_config = arize._generated.api_client.models.template_config.TemplateConfig(
                    name = '', 
                    template = '', 
                    include_explanations = True, 
                    use_function_calling_if_available = True, 
                    classification_choices = {
                        'key' : 1.337
                        }, 
                    direction = 'maximize', 
                    data_granularity = 'span', 
                    llm_config = arize._generated.api_client.models.evaluator_llm_config.EvaluatorLlmConfig(
                        ai_integration_id = '', 
                        model_name = '', 
                        invocation_parameters = arize._generated.api_client.models.invocation_params.InvocationParams(
                            temperature = 1.337, 
                            max_tokens = 56, 
                            max_completion_tokens = 56, 
                            top_p = 1.337, 
                            frequency_penalty = 1.337, 
                            presence_penalty = 1.337, 
                            stop = [
                                ''
                                ], 
                            response_format = arize._generated.api_client.models.response_format.ResponseFormat(
                                type = 'text', 
                                json_schema = arize._generated.api_client.models.response_format_json_schema.ResponseFormat_json_schema(
                                    name = '', 
                                    description = '', 
                                    schema = arize._generated.api_client.models.schema.schema(), 
                                    strict = True, ), ), 
                            tool_config = arize._generated.api_client.models.tool_config.ToolConfig(
                                tools = [
                                    None
                                    ], 
                                tool_choice = null, ), ), 
                        provider_parameters = arize._generated.api_client.models.provider_params.ProviderParams(
                            azure_params = arize._generated.api_client.models.provider_params_azure_params.ProviderParams_azure_params(
                                azure_deployment_name = '', 
                                azure_openai_endpoint = '', 
                                azure_openai_version = '', ), 
                            anthropic_headers = arize._generated.api_client.models.provider_params_anthropic_headers.ProviderParams_anthropic_headers(
                                anthropic_beta = [
                                    ''
                                    ], ), 
                            anthropic_version = '', 
                            bedrock_options = arize._generated.api_client.models.provider_params_bedrock_options.ProviderParams_bedrock_options(
                                use_converse_endpoint = True, ), 
                            region = '', ), ), )
            )
        else:
            return EvaluatorVersionTemplate(
                id = '',
                evaluator_id = '',
                commit_hash = '',
                commit_message = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user_id = '',
                type = 'template',
                template_config = arize._generated.api_client.models.template_config.TemplateConfig(
                    name = '', 
                    template = '', 
                    include_explanations = True, 
                    use_function_calling_if_available = True, 
                    classification_choices = {
                        'key' : 1.337
                        }, 
                    direction = 'maximize', 
                    data_granularity = 'span', 
                    llm_config = arize._generated.api_client.models.evaluator_llm_config.EvaluatorLlmConfig(
                        ai_integration_id = '', 
                        model_name = '', 
                        invocation_parameters = arize._generated.api_client.models.invocation_params.InvocationParams(
                            temperature = 1.337, 
                            max_tokens = 56, 
                            max_completion_tokens = 56, 
                            top_p = 1.337, 
                            frequency_penalty = 1.337, 
                            presence_penalty = 1.337, 
                            stop = [
                                ''
                                ], 
                            response_format = arize._generated.api_client.models.response_format.ResponseFormat(
                                type = 'text', 
                                json_schema = arize._generated.api_client.models.response_format_json_schema.ResponseFormat_json_schema(
                                    name = '', 
                                    description = '', 
                                    schema = arize._generated.api_client.models.schema.schema(), 
                                    strict = True, ), ), 
                            tool_config = arize._generated.api_client.models.tool_config.ToolConfig(
                                tools = [
                                    None
                                    ], 
                                tool_choice = null, ), ), 
                        provider_parameters = arize._generated.api_client.models.provider_params.ProviderParams(
                            azure_params = arize._generated.api_client.models.provider_params_azure_params.ProviderParams_azure_params(
                                azure_deployment_name = '', 
                                azure_openai_endpoint = '', 
                                azure_openai_version = '', ), 
                            anthropic_headers = arize._generated.api_client.models.provider_params_anthropic_headers.ProviderParams_anthropic_headers(
                                anthropic_beta = [
                                    ''
                                    ], ), 
                            anthropic_version = '', 
                            bedrock_options = arize._generated.api_client.models.provider_params_bedrock_options.ProviderParams_bedrock_options(
                                use_converse_endpoint = True, ), 
                            region = '', ), ), ),
        )
        """

    def testEvaluatorVersionTemplate(self):
        """Test EvaluatorVersionTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
